### ISSUE TITLE
Issue with the precompiled binaries

### ISSUE THREAD

**Issue by Cyb3rGh0st786** [gatariee/gocheck#1]
Hello @gatariee ,

I have tried use the precompiled binaries and I get error when I use it on windows 10 64 bit version. Also tried it on windows server 2016 

```
C:\Users\Administrator\Downloads>gocheck64.exe
This version of C:\Users\Administrator\Downloads\gocheck64.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```

![image](https://github.com/gatariee/gocheck/assets/7692857/18c81475-d3ac-4552-968f-11adcc340748)

**Comment by gatariee** [comment]
fixed in [7f4b618](https://github.com/gatariee/gocheck/commit/7f4b618bac42a4d948cff7763655ed425124b3f4)
