### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by dobin** [gatariee/gocheck#3]
If you want to invest more research into this. 

There's an implementation which also can detect multiple matches, not just one: https://github.com/dobin/avred/blob/main/reducer.py

Talk: https://www.youtube.com/watch?v=Sxw8K6gFSbg

**Comment by gatariee** [comment]
hey dobin, great work! :)

ill definitely look more into matching multiple chunks, will give you credits if/when i get to it

**Comment by dobin** [comment]
I like to see rewrites in Go, and general improvements in security research :-)
