### ISSUE TITLE
multi signature situation

### ISSUE THREAD

**Issue by wan-xiang** [gatariee/gocheck#7]
May I ask, does GoCheck have any methods for handling multiple  signatures, such as simultaneously checking the PE export table and the code in the text section?

**Comment by gatariee** [comment]
no, if you're interested you can look into avred instead 
https://avred.r00ted.ch/examples

**Comment by wan-xiang** [comment]
> no, if you're interested you can look into avred instead https://avred.r00ted.ch/examples

Thanks for your reply. Have a good day.
